FROM jonasbonno/rpi-grovepi


MAINTAINER Jonas Bonno Mikkelsen (https://github.com/JonasBonno)


# Define working directory.
WORKDIR /data


# Define default command.
CMD ["/usr/bin/python", "/data/python/main.py"]
