FROM hypriot/rpi-python


MAINTAINER Jonas Bonno Mikkelsen (https://github.com/JonasBonno)


# Define working directory.
WORKDIR /data


# Define default command.
CMD ["/env/bin/python", "/data/python/main.py"]
